/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Schedule struct {
	Periodic bool `json:"periodic,omitempty"`

	Finished bool `json:"finished,omitempty"`

	NextTime string `json:"nextTime,omitempty"`

	Span string `json:"span"`
}

// AssertScheduleRequired checks if the required fields are not zero-ed
func AssertScheduleRequired(obj Schedule) error {
	elements := map[string]interface{}{
		"span": obj.Span,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseScheduleRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Schedule (e.g. [][]Schedule), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseScheduleRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSchedule, ok := obj.(Schedule)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertScheduleRequired(aSchedule)
	})
}
