/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GrantAdminRequest struct {
	Login string `json:"login"`
}

// AssertGrantAdminRequestRequired checks if the required fields are not zero-ed
func AssertGrantAdminRequestRequired(obj GrantAdminRequest) error {
	elements := map[string]interface{}{
		"login": obj.Login,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGrantAdminRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GrantAdminRequest (e.g. [][]GrantAdminRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGrantAdminRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGrantAdminRequest, ok := obj.(GrantAdminRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGrantAdminRequestRequired(aGrantAdminRequest)
	})
}
