/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteClientRequest struct {
	Id string `json:"id"`
}

// AssertDeleteClientRequestRequired checks if the required fields are not zero-ed
func AssertDeleteClientRequestRequired(obj DeleteClientRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeleteClientRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DeleteClientRequest (e.g. [][]DeleteClientRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeleteClientRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeleteClientRequest, ok := obj.(DeleteClientRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeleteClientRequestRequired(aDeleteClientRequest)
	})
}
