/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEventResponse struct {
	Passed bool `json:"passed"`
}

// AssertCreateEventResponseRequired checks if the required fields are not zero-ed
func AssertCreateEventResponseRequired(obj CreateEventResponse) error {
	elements := map[string]interface{}{
		"passed": obj.Passed,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateEventResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateEventResponse (e.g. [][]CreateEventResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateEventResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateEventResponse, ok := obj.(CreateEventResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateEventResponseRequired(aCreateEventResponse)
	})
}
