/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FilterResponse struct {
	Count int32 `json:"count"`
}

// AssertFilterResponseRequired checks if the required fields are not zero-ed
func AssertFilterResponseRequired(obj FilterResponse) error {
	elements := map[string]interface{}{
		"count": obj.Count,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseFilterResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FilterResponse (e.g. [][]FilterResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFilterResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilterResponse, ok := obj.(FilterResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFilterResponseRequired(aFilterResponse)
	})
}
