/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthRequest struct {
	Login string `json:"login"`

	Password string `json:"password"`
}

// AssertAuthRequestRequired checks if the required fields are not zero-ed
func AssertAuthRequestRequired(obj AuthRequest) error {
	elements := map[string]interface{}{
		"login":    obj.Login,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAuthRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuthRequest (e.g. [][]AuthRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuthRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuthRequest, ok := obj.(AuthRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuthRequestRequired(aAuthRequest)
	})
}
