/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetUserRequest struct {
	Login string `json:"login"`
}

// AssertGetUserRequestRequired checks if the required fields are not zero-ed
func AssertGetUserRequestRequired(obj GetUserRequest) error {
	elements := map[string]interface{}{
		"login": obj.Login,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGetUserRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetUserRequest (e.g. [][]GetUserRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetUserRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetUserRequest, ok := obj.(GetUserRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetUserRequestRequired(aGetUserRequest)
	})
}
