/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FilterRequest struct {
	Filters []Filter `json:"filters"`
}

// AssertFilterRequestRequired checks if the required fields are not zero-ed
func AssertFilterRequestRequired(obj FilterRequest) error {
	elements := map[string]interface{}{
		"filters": obj.Filters,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Filters {
		if err := AssertFilterRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseFilterRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FilterRequest (e.g. [][]FilterRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFilterRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilterRequest, ok := obj.(FilterRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFilterRequestRequired(aFilterRequest)
	})
}
