/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateAdResponse struct {
	Created bool `json:"created"`
}

// AssertCreateAdResponseRequired checks if the required fields are not zero-ed
func AssertCreateAdResponseRequired(obj CreateAdResponse) error {
	elements := map[string]interface{}{
		"created": obj.Created,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateAdResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateAdResponse (e.g. [][]CreateAdResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateAdResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateAdResponse, ok := obj.(CreateAdResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateAdResponseRequired(aCreateAdResponse)
	})
}
