/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEventTypeResponse struct {
	Created bool `json:"created"`
}

// AssertCreateEventTypeResponseRequired checks if the required fields are not zero-ed
func AssertCreateEventTypeResponseRequired(obj CreateEventTypeResponse) error {
	elements := map[string]interface{}{
		"created": obj.Created,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateEventTypeResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateEventTypeResponse (e.g. [][]CreateEventTypeResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateEventTypeResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateEventTypeResponse, ok := obj.(CreateEventTypeResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateEventTypeResponseRequired(aCreateEventTypeResponse)
	})
}
