/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AdStat struct {
	Num int32 `json:"num"`

	Date string `json:"date"`
}

// AssertAdStatRequired checks if the required fields are not zero-ed
func AssertAdStatRequired(obj AdStat) error {
	elements := map[string]interface{}{
		"num":  obj.Num,
		"date": obj.Date,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAdStatRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AdStat (e.g. [][]AdStat), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAdStatRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAdStat, ok := obj.(AdStat)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAdStatRequired(aAdStat)
	})
}
