/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetClientResponse struct {
	Client Client `json:"client"`
}

// AssertGetClientResponseRequired checks if the required fields are not zero-ed
func AssertGetClientResponseRequired(obj GetClientResponse) error {
	elements := map[string]interface{}{
		"client": obj.Client,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertClientRequired(obj.Client); err != nil {
		return err
	}
	return nil
}

// AssertRecurseGetClientResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetClientResponse (e.g. [][]GetClientResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetClientResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetClientResponse, ok := obj.(GetClientResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetClientResponseRequired(aGetClientResponse)
	})
}
