/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateClientRequest struct {
	Client Client `json:"client"`
}

// AssertCreateClientRequestRequired checks if the required fields are not zero-ed
func AssertCreateClientRequestRequired(obj CreateClientRequest) error {
	elements := map[string]interface{}{
		"client": obj.Client,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertClientRequired(obj.Client); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateClientRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateClientRequest (e.g. [][]CreateClientRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateClientRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateClientRequest, ok := obj.(CreateClientRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateClientRequestRequired(aCreateClientRequest)
	})
}
