/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateAdRequest struct {
	Ad Ad `json:"ad"`
}

// AssertCreateAdRequestRequired checks if the required fields are not zero-ed
func AssertCreateAdRequestRequired(obj CreateAdRequest) error {
	elements := map[string]interface{}{
		"ad": obj.Ad,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAdRequired(obj.Ad); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateAdRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateAdRequest (e.g. [][]CreateAdRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateAdRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateAdRequest, ok := obj.(CreateAdRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateAdRequestRequired(aCreateAdRequest)
	})
}
