/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteClientResponse struct {
	Deleted bool `json:"deleted"`
}

// AssertDeleteClientResponseRequired checks if the required fields are not zero-ed
func AssertDeleteClientResponseRequired(obj DeleteClientResponse) error {
	elements := map[string]interface{}{
		"deleted": obj.Deleted,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeleteClientResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DeleteClientResponse (e.g. [][]DeleteClientResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeleteClientResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeleteClientResponse, ok := obj.(DeleteClientResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeleteClientResponseRequired(aDeleteClientResponse)
	})
}
