/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FilterFilter struct {
	Alias string `json:"alias,omitempty"`

	Span string `json:"span,omitempty"`

	Rate int32 `json:"rate,omitempty"`

	Field string `json:"field,omitempty"`

	Cmp string `json:"cmp,omitempty"`

	Value1 string `json:"value1,omitempty"`

	Value2 string `json:"value2,omitempty"`
}

// AssertFilterFilterRequired checks if the required fields are not zero-ed
func AssertFilterFilterRequired(obj FilterFilter) error {
	return nil
}

// AssertRecurseFilterFilterRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FilterFilter (e.g. [][]FilterFilter), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFilterFilterRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilterFilter, ok := obj.(FilterFilter)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFilterFilterRequired(aFilterFilter)
	})
}
