/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GrantAdminResponse struct {
	Granted bool `json:"granted"`
}

// AssertGrantAdminResponseRequired checks if the required fields are not zero-ed
func AssertGrantAdminResponseRequired(obj GrantAdminResponse) error {
	elements := map[string]interface{}{
		"granted": obj.Granted,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGrantAdminResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GrantAdminResponse (e.g. [][]GrantAdminResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGrantAdminResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGrantAdminResponse, ok := obj.(GrantAdminResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGrantAdminResponseRequired(aGrantAdminResponse)
	})
}
