/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAdsResponse struct {
	Ads []Ad `json:"ads"`
}

// AssertGetAdsResponseRequired checks if the required fields are not zero-ed
func AssertGetAdsResponseRequired(obj GetAdsResponse) error {
	elements := map[string]interface{}{
		"ads": obj.Ads,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Ads {
		if err := AssertAdRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetAdsResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetAdsResponse (e.g. [][]GetAdsResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetAdsResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetAdsResponse, ok := obj.(GetAdsResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetAdsResponseRequired(aGetAdsResponse)
	})
}
