/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetClientStatsResponse struct {
	ClientStats ClientStats `json:"clientStats"`

	AdStats []AdStat `json:"adStats"`
}

// AssertGetClientStatsResponseRequired checks if the required fields are not zero-ed
func AssertGetClientStatsResponseRequired(obj GetClientStatsResponse) error {
	elements := map[string]interface{}{
		"clientStats": obj.ClientStats,
		"adStats":     obj.AdStats,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertClientStatsRequired(obj.ClientStats); err != nil {
		return err
	}
	for _, el := range obj.AdStats {
		if err := AssertAdStatRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetClientStatsResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetClientStatsResponse (e.g. [][]GetClientStatsResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetClientStatsResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetClientStatsResponse, ok := obj.(GetClientStatsResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetClientStatsResponseRequired(aGetClientStatsResponse)
	})
}
