/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteUserRequest struct {
	Login string `json:"login"`
}

// AssertDeleteUserRequestRequired checks if the required fields are not zero-ed
func AssertDeleteUserRequestRequired(obj DeleteUserRequest) error {
	elements := map[string]interface{}{
		"login": obj.Login,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeleteUserRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DeleteUserRequest (e.g. [][]DeleteUserRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeleteUserRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeleteUserRequest, ok := obj.(DeleteUserRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeleteUserRequestRequired(aDeleteUserRequest)
	})
}
