/*
 * API for course project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEventRequest struct {
	Event Event `json:"event"`
}

// AssertCreateEventRequestRequired checks if the required fields are not zero-ed
func AssertCreateEventRequestRequired(obj CreateEventRequest) error {
	elements := map[string]interface{}{
		"event": obj.Event,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertEventRequired(obj.Event); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateEventRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateEventRequest (e.g. [][]CreateEventRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateEventRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateEventRequest, ok := obj.(CreateEventRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateEventRequestRequired(aCreateEventRequest)
	})
}
