/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetClientStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClientStatsResponse{}

// GetClientStatsResponse struct for GetClientStatsResponse
type GetClientStatsResponse struct {
	ClientStats ClientStats `json:"clientStats"`
	AdStats     []AdStat    `json:"adStats"`
}

// NewGetClientStatsResponse instantiates a new GetClientStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientStatsResponse(clientStats ClientStats, adStats []AdStat) *GetClientStatsResponse {
	this := GetClientStatsResponse{}
	this.ClientStats = clientStats
	this.AdStats = adStats
	return &this
}

// NewGetClientStatsResponseWithDefaults instantiates a new GetClientStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientStatsResponseWithDefaults() *GetClientStatsResponse {
	this := GetClientStatsResponse{}
	return &this
}

// GetClientStats returns the ClientStats field value
func (o *GetClientStatsResponse) GetClientStats() ClientStats {
	if o == nil {
		var ret ClientStats
		return ret
	}

	return o.ClientStats
}

// GetClientStatsOk returns a tuple with the ClientStats field value
// and a boolean to check if the value has been set.
func (o *GetClientStatsResponse) GetClientStatsOk() (*ClientStats, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientStats, true
}

// SetClientStats sets field value
func (o *GetClientStatsResponse) SetClientStats(v ClientStats) {
	o.ClientStats = v
}

// GetAdStats returns the AdStats field value
func (o *GetClientStatsResponse) GetAdStats() []AdStat {
	if o == nil {
		var ret []AdStat
		return ret
	}

	return o.AdStats
}

// GetAdStatsOk returns a tuple with the AdStats field value
// and a boolean to check if the value has been set.
func (o *GetClientStatsResponse) GetAdStatsOk() ([]AdStat, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdStats, true
}

// SetAdStats sets field value
func (o *GetClientStatsResponse) SetAdStats(v []AdStat) {
	o.AdStats = v
}

func (o GetClientStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClientStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientStats"] = o.ClientStats
	toSerialize["adStats"] = o.AdStats
	return toSerialize, nil
}

type NullableGetClientStatsResponse struct {
	value *GetClientStatsResponse
	isSet bool
}

func (v NullableGetClientStatsResponse) Get() *GetClientStatsResponse {
	return v.value
}

func (v *NullableGetClientStatsResponse) Set(val *GetClientStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientStatsResponse(val *GetClientStatsResponse) *NullableGetClientStatsResponse {
	return &NullableGetClientStatsResponse{value: val, isSet: true}
}

func (v NullableGetClientStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
