/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterResponse{}

// FilterResponse struct for FilterResponse
type FilterResponse struct {
	Count int32 `json:"count"`
}

// NewFilterResponse instantiates a new FilterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterResponse(count int32) *FilterResponse {
	this := FilterResponse{}
	this.Count = count
	return &this
}

// NewFilterResponseWithDefaults instantiates a new FilterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterResponseWithDefaults() *FilterResponse {
	this := FilterResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *FilterResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *FilterResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *FilterResponse) SetCount(v int32) {
	o.Count = v
}

func (o FilterResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

type NullableFilterResponse struct {
	value *FilterResponse
	isSet bool
}

func (v NullableFilterResponse) Get() *FilterResponse {
	return v.value
}

func (v *NullableFilterResponse) Set(val *FilterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterResponse(val *FilterResponse) *NullableFilterResponse {
	return &NullableFilterResponse{value: val, isSet: true}
}

func (v NullableFilterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
