/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetClientsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClientsResponse{}

// GetClientsResponse struct for GetClientsResponse
type GetClientsResponse struct {
	Clients []Client `json:"clients"`
}

// NewGetClientsResponse instantiates a new GetClientsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientsResponse(clients []Client) *GetClientsResponse {
	this := GetClientsResponse{}
	this.Clients = clients
	return &this
}

// NewGetClientsResponseWithDefaults instantiates a new GetClientsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientsResponseWithDefaults() *GetClientsResponse {
	this := GetClientsResponse{}
	return &this
}

// GetClients returns the Clients field value
func (o *GetClientsResponse) GetClients() []Client {
	if o == nil {
		var ret []Client
		return ret
	}

	return o.Clients
}

// GetClientsOk returns a tuple with the Clients field value
// and a boolean to check if the value has been set.
func (o *GetClientsResponse) GetClientsOk() ([]Client, bool) {
	if o == nil {
		return nil, false
	}
	return o.Clients, true
}

// SetClients sets field value
func (o *GetClientsResponse) SetClients(v []Client) {
	o.Clients = v
}

func (o GetClientsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClientsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clients"] = o.Clients
	return toSerialize, nil
}

type NullableGetClientsResponse struct {
	value *GetClientsResponse
	isSet bool
}

func (v NullableGetClientsResponse) Get() *GetClientsResponse {
	return v.value
}

func (v *NullableGetClientsResponse) Set(val *GetClientsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientsResponse(val *GetClientsResponse) *NullableGetClientsResponse {
	return &NullableGetClientsResponse{value: val, isSet: true}
}

func (v NullableGetClientsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
