/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Ad type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ad{}

// Ad struct for Ad
type Ad struct {
	Content    string   `json:"content"`
	CreateTime *string  `json:"create_time,omitempty"`
	Filters    []Filter `json:"filters,omitempty"`
	UserID     string   `json:"userID"`
	Schedule   Schedule `json:"schedule"`
}

// NewAd instantiates a new Ad object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAd(content string, userID string, schedule Schedule) *Ad {
	this := Ad{}
	this.Content = content
	this.UserID = userID
	this.Schedule = schedule
	return &this
}

// NewAdWithDefaults instantiates a new Ad object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdWithDefaults() *Ad {
	this := Ad{}
	return &this
}

// GetContent returns the Content field value
func (o *Ad) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *Ad) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *Ad) SetContent(v string) {
	o.Content = v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *Ad) GetCreateTime() string {
	if o == nil || IsNil(o.CreateTime) {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Ad) GetCreateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *Ad) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *Ad) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *Ad) GetFilters() []Filter {
	if o == nil || IsNil(o.Filters) {
		var ret []Filter
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Ad) GetFiltersOk() ([]Filter, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *Ad) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []Filter and assigns it to the Filters field.
func (o *Ad) SetFilters(v []Filter) {
	o.Filters = v
}

// GetUserID returns the UserID field value
func (o *Ad) GetUserID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *Ad) GetUserIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *Ad) SetUserID(v string) {
	o.UserID = v
}

// GetSchedule returns the Schedule field value
func (o *Ad) GetSchedule() Schedule {
	if o == nil {
		var ret Schedule
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *Ad) GetScheduleOk() (*Schedule, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *Ad) SetSchedule(v Schedule) {
	o.Schedule = v
}

func (o Ad) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ad) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	if !IsNil(o.CreateTime) {
		toSerialize["create_time"] = o.CreateTime
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["userID"] = o.UserID
	toSerialize["schedule"] = o.Schedule
	return toSerialize, nil
}

type NullableAd struct {
	value *Ad
	isSet bool
}

func (v NullableAd) Get() *Ad {
	return v.value
}

func (v *NullableAd) Set(val *Ad) {
	v.value = val
	v.isSet = true
}

func (v NullableAd) IsSet() bool {
	return v.isSet
}

func (v *NullableAd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAd(val *Ad) *NullableAd {
	return &NullableAd{value: val, isSet: true}
}

func (v NullableAd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
