/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateEventTypeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEventTypeResponse{}

// CreateEventTypeResponse struct for CreateEventTypeResponse
type CreateEventTypeResponse struct {
	Created bool `json:"created"`
}

// NewCreateEventTypeResponse instantiates a new CreateEventTypeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventTypeResponse(created bool) *CreateEventTypeResponse {
	this := CreateEventTypeResponse{}
	this.Created = created
	return &this
}

// NewCreateEventTypeResponseWithDefaults instantiates a new CreateEventTypeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventTypeResponseWithDefaults() *CreateEventTypeResponse {
	this := CreateEventTypeResponse{}
	return &this
}

// GetCreated returns the Created field value
func (o *CreateEventTypeResponse) GetCreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CreateEventTypeResponse) GetCreatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CreateEventTypeResponse) SetCreated(v bool) {
	o.Created = v
}

func (o CreateEventTypeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEventTypeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	return toSerialize, nil
}

type NullableCreateEventTypeResponse struct {
	value *CreateEventTypeResponse
	isSet bool
}

func (v NullableCreateEventTypeResponse) Get() *CreateEventTypeResponse {
	return v.value
}

func (v *NullableCreateEventTypeResponse) Set(val *CreateEventTypeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventTypeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventTypeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventTypeResponse(val *CreateEventTypeResponse) *NullableCreateEventTypeResponse {
	return &NullableCreateEventTypeResponse{value: val, isSet: true}
}

func (v NullableCreateEventTypeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventTypeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
