/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GrantAdminRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantAdminRequest{}

// GrantAdminRequest struct for GrantAdminRequest
type GrantAdminRequest struct {
	Login string `json:"login"`
}

// NewGrantAdminRequest instantiates a new GrantAdminRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantAdminRequest(login string) *GrantAdminRequest {
	this := GrantAdminRequest{}
	this.Login = login
	return &this
}

// NewGrantAdminRequestWithDefaults instantiates a new GrantAdminRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantAdminRequestWithDefaults() *GrantAdminRequest {
	this := GrantAdminRequest{}
	return &this
}

// GetLogin returns the Login field value
func (o *GrantAdminRequest) GetLogin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Login
}

// GetLoginOk returns a tuple with the Login field value
// and a boolean to check if the value has been set.
func (o *GrantAdminRequest) GetLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Login, true
}

// SetLogin sets field value
func (o *GrantAdminRequest) SetLogin(v string) {
	o.Login = v
}

func (o GrantAdminRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantAdminRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["login"] = o.Login
	return toSerialize, nil
}

type NullableGrantAdminRequest struct {
	value *GrantAdminRequest
	isSet bool
}

func (v NullableGrantAdminRequest) Get() *GrantAdminRequest {
	return v.value
}

func (v *NullableGrantAdminRequest) Set(val *GrantAdminRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantAdminRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantAdminRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantAdminRequest(val *GrantAdminRequest) *NullableGrantAdminRequest {
	return &NullableGrantAdminRequest{value: val, isSet: true}
}

func (v NullableGrantAdminRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantAdminRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
