/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Client type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Client{}

// Client struct for Client
type Client struct {
	Id               string            `json:"id"`
	Name             string            `json:"name"`
	Surname          string            `json:"surname"`
	Patronymic       string            `json:"patronymic"`
	Gender           string            `json:"gender"`
	BirthDate        string            `json:"birth_date"`
	RegistrationDate string            `json:"registration_date"`
	Email            string            `json:"email"`
	Data             map[string]string `json:"data"`
}

// NewClient instantiates a new Client object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClient(id string, name string, surname string, patronymic string, gender string, birthDate string, registrationDate string, email string, data map[string]string) *Client {
	this := Client{}
	this.Id = id
	this.Name = name
	this.Surname = surname
	this.Patronymic = patronymic
	this.Gender = gender
	this.BirthDate = birthDate
	this.RegistrationDate = registrationDate
	this.Email = email
	this.Data = data
	return &this
}

// NewClientWithDefaults instantiates a new Client object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientWithDefaults() *Client {
	this := Client{}
	return &this
}

// GetId returns the Id field value
func (o *Client) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Client) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Client) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Client) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Client) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Client) SetName(v string) {
	o.Name = v
}

// GetSurname returns the Surname field value
func (o *Client) GetSurname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Surname
}

// GetSurnameOk returns a tuple with the Surname field value
// and a boolean to check if the value has been set.
func (o *Client) GetSurnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Surname, true
}

// SetSurname sets field value
func (o *Client) SetSurname(v string) {
	o.Surname = v
}

// GetPatronymic returns the Patronymic field value
func (o *Client) GetPatronymic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Patronymic
}

// GetPatronymicOk returns a tuple with the Patronymic field value
// and a boolean to check if the value has been set.
func (o *Client) GetPatronymicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Patronymic, true
}

// SetPatronymic sets field value
func (o *Client) SetPatronymic(v string) {
	o.Patronymic = v
}

// GetGender returns the Gender field value
func (o *Client) GetGender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *Client) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *Client) SetGender(v string) {
	o.Gender = v
}

// GetBirthDate returns the BirthDate field value
func (o *Client) GetBirthDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BirthDate
}

// GetBirthDateOk returns a tuple with the BirthDate field value
// and a boolean to check if the value has been set.
func (o *Client) GetBirthDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BirthDate, true
}

// SetBirthDate sets field value
func (o *Client) SetBirthDate(v string) {
	o.BirthDate = v
}

// GetRegistrationDate returns the RegistrationDate field value
func (o *Client) GetRegistrationDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationDate
}

// GetRegistrationDateOk returns a tuple with the RegistrationDate field value
// and a boolean to check if the value has been set.
func (o *Client) GetRegistrationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationDate, true
}

// SetRegistrationDate sets field value
func (o *Client) SetRegistrationDate(v string) {
	o.RegistrationDate = v
}

// GetEmail returns the Email field value
func (o *Client) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Client) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Client) SetEmail(v string) {
	o.Email = v
}

// GetData returns the Data field value
func (o *Client) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Client) GetDataOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Client) SetData(v map[string]string) {
	o.Data = v
}

func (o Client) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Client) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["surname"] = o.Surname
	toSerialize["patronymic"] = o.Patronymic
	toSerialize["gender"] = o.Gender
	toSerialize["birth_date"] = o.BirthDate
	toSerialize["registration_date"] = o.RegistrationDate
	toSerialize["email"] = o.Email
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableClient struct {
	value *Client
	isSet bool
}

func (v NullableClient) Get() *Client {
	return v.value
}

func (v *NullableClient) Set(val *Client) {
	v.value = val
	v.isSet = true
}

func (v NullableClient) IsSet() bool {
	return v.isSet
}

func (v *NullableClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClient(val *Client) *NullableClient {
	return &NullableClient{value: val, isSet: true}
}

func (v NullableClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
