/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClientRequest{}

// CreateClientRequest struct for CreateClientRequest
type CreateClientRequest struct {
	Client Client `json:"client"`
}

// NewCreateClientRequest instantiates a new CreateClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClientRequest(client Client) *CreateClientRequest {
	this := CreateClientRequest{}
	this.Client = client
	return &this
}

// NewCreateClientRequestWithDefaults instantiates a new CreateClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClientRequestWithDefaults() *CreateClientRequest {
	this := CreateClientRequest{}
	return &this
}

// GetClient returns the Client field value
func (o *CreateClientRequest) GetClient() Client {
	if o == nil {
		var ret Client
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *CreateClientRequest) GetClientOk() (*Client, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *CreateClientRequest) SetClient(v Client) {
	o.Client = v
}

func (o CreateClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client"] = o.Client
	return toSerialize, nil
}

type NullableCreateClientRequest struct {
	value *CreateClientRequest
	isSet bool
}

func (v NullableCreateClientRequest) Get() *CreateClientRequest {
	return v.value
}

func (v *NullableCreateClientRequest) Set(val *CreateClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClientRequest(val *CreateClientRequest) *NullableCreateClientRequest {
	return &NullableCreateClientRequest{value: val, isSet: true}
}

func (v NullableCreateClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
