/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteClientRequest{}

// DeleteClientRequest struct for DeleteClientRequest
type DeleteClientRequest struct {
	Id string `json:"id"`
}

// NewDeleteClientRequest instantiates a new DeleteClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteClientRequest(id string) *DeleteClientRequest {
	this := DeleteClientRequest{}
	this.Id = id
	return &this
}

// NewDeleteClientRequestWithDefaults instantiates a new DeleteClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteClientRequestWithDefaults() *DeleteClientRequest {
	this := DeleteClientRequest{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteClientRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteClientRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteClientRequest) SetId(v string) {
	o.Id = v
}

func (o DeleteClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableDeleteClientRequest struct {
	value *DeleteClientRequest
	isSet bool
}

func (v NullableDeleteClientRequest) Get() *DeleteClientRequest {
	return v.value
}

func (v *NullableDeleteClientRequest) Set(val *DeleteClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteClientRequest(val *DeleteClientRequest) *NullableDeleteClientRequest {
	return &NullableDeleteClientRequest{value: val, isSet: true}
}

func (v NullableDeleteClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
