/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAdRequest{}

// CreateAdRequest struct for CreateAdRequest
type CreateAdRequest struct {
	Ad Ad `json:"ad"`
}

// NewCreateAdRequest instantiates a new CreateAdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAdRequest(ad Ad) *CreateAdRequest {
	this := CreateAdRequest{}
	this.Ad = ad
	return &this
}

// NewCreateAdRequestWithDefaults instantiates a new CreateAdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAdRequestWithDefaults() *CreateAdRequest {
	this := CreateAdRequest{}
	return &this
}

// GetAd returns the Ad field value
func (o *CreateAdRequest) GetAd() Ad {
	if o == nil {
		var ret Ad
		return ret
	}

	return o.Ad
}

// GetAdOk returns a tuple with the Ad field value
// and a boolean to check if the value has been set.
func (o *CreateAdRequest) GetAdOk() (*Ad, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ad, true
}

// SetAd sets field value
func (o *CreateAdRequest) SetAd(v Ad) {
	o.Ad = v
}

func (o CreateAdRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ad"] = o.Ad
	return toSerialize, nil
}

type NullableCreateAdRequest struct {
	value *CreateAdRequest
	isSet bool
}

func (v NullableCreateAdRequest) Get() *CreateAdRequest {
	return v.value
}

func (v *NullableCreateAdRequest) Set(val *CreateAdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAdRequest(val *CreateAdRequest) *NullableCreateAdRequest {
	return &NullableCreateAdRequest{value: val, isSet: true}
}

func (v NullableCreateAdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
