/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAdResponse{}

// CreateAdResponse struct for CreateAdResponse
type CreateAdResponse struct {
	Created bool `json:"created"`
}

// NewCreateAdResponse instantiates a new CreateAdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAdResponse(created bool) *CreateAdResponse {
	this := CreateAdResponse{}
	this.Created = created
	return &this
}

// NewCreateAdResponseWithDefaults instantiates a new CreateAdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAdResponseWithDefaults() *CreateAdResponse {
	this := CreateAdResponse{}
	return &this
}

// GetCreated returns the Created field value
func (o *CreateAdResponse) GetCreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CreateAdResponse) GetCreatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CreateAdResponse) SetCreated(v bool) {
	o.Created = v
}

func (o CreateAdResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	return toSerialize, nil
}

type NullableCreateAdResponse struct {
	value *CreateAdResponse
	isSet bool
}

func (v NullableCreateAdResponse) Get() *CreateAdResponse {
	return v.value
}

func (v *NullableCreateAdResponse) Set(val *CreateAdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAdResponse(val *CreateAdResponse) *NullableCreateAdResponse {
	return &NullableCreateAdResponse{value: val, isSet: true}
}

func (v NullableCreateAdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
