/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetUserByIDRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserByIDRequest{}

// GetUserByIDRequest struct for GetUserByIDRequest
type GetUserByIDRequest struct {
	Id string `json:"id"`
}

// NewGetUserByIDRequest instantiates a new GetUserByIDRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserByIDRequest(id string) *GetUserByIDRequest {
	this := GetUserByIDRequest{}
	this.Id = id
	return &this
}

// NewGetUserByIDRequestWithDefaults instantiates a new GetUserByIDRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserByIDRequestWithDefaults() *GetUserByIDRequest {
	this := GetUserByIDRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetUserByIDRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetUserByIDRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetUserByIDRequest) SetId(v string) {
	o.Id = v
}

func (o GetUserByIDRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserByIDRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGetUserByIDRequest struct {
	value *GetUserByIDRequest
	isSet bool
}

func (v NullableGetUserByIDRequest) Get() *GetUserByIDRequest {
	return v.value
}

func (v *NullableGetUserByIDRequest) Set(val *GetUserByIDRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserByIDRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserByIDRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserByIDRequest(val *GetUserByIDRequest) *NullableGetUserByIDRequest {
	return &NullableGetUserByIDRequest{value: val, isSet: true}
}

func (v NullableGetUserByIDRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserByIDRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
