/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteClientResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteClientResponse{}

// DeleteClientResponse struct for DeleteClientResponse
type DeleteClientResponse struct {
	Deleted bool `json:"deleted"`
}

// NewDeleteClientResponse instantiates a new DeleteClientResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteClientResponse(deleted bool) *DeleteClientResponse {
	this := DeleteClientResponse{}
	this.Deleted = deleted
	return &this
}

// NewDeleteClientResponseWithDefaults instantiates a new DeleteClientResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteClientResponseWithDefaults() *DeleteClientResponse {
	this := DeleteClientResponse{}
	return &this
}

// GetDeleted returns the Deleted field value
func (o *DeleteClientResponse) GetDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *DeleteClientResponse) GetDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deleted, true
}

// SetDeleted sets field value
func (o *DeleteClientResponse) SetDeleted(v bool) {
	o.Deleted = v
}

func (o DeleteClientResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteClientResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deleted"] = o.Deleted
	return toSerialize, nil
}

type NullableDeleteClientResponse struct {
	value *DeleteClientResponse
	isSet bool
}

func (v NullableDeleteClientResponse) Get() *DeleteClientResponse {
	return v.value
}

func (v *NullableDeleteClientResponse) Set(val *DeleteClientResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteClientResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteClientResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteClientResponse(val *DeleteClientResponse) *NullableDeleteClientResponse {
	return &NullableDeleteClientResponse{value: val, isSet: true}
}

func (v NullableDeleteClientResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteClientResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
