/*
API for course project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClientRequest{}

// GetClientRequest struct for GetClientRequest
type GetClientRequest struct {
	Id string `json:"id"`
}

// NewGetClientRequest instantiates a new GetClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientRequest(id string) *GetClientRequest {
	this := GetClientRequest{}
	this.Id = id
	return &this
}

// NewGetClientRequestWithDefaults instantiates a new GetClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientRequestWithDefaults() *GetClientRequest {
	this := GetClientRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetClientRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetClientRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetClientRequest) SetId(v string) {
	o.Id = v
}

func (o GetClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGetClientRequest struct {
	value *GetClientRequest
	isSet bool
}

func (v NullableGetClientRequest) Get() *GetClientRequest {
	return v.value
}

func (v *NullableGetClientRequest) Set(val *GetClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientRequest(val *GetClientRequest) *NullableGetClientRequest {
	return &NullableGetClientRequest{value: val, isSet: true}
}

func (v NullableGetClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
