version: "3.9"
services:
  postgres-coursework:
    image: postgres:latest
    environment:
      POSTGRES_DB: "coursework"
      POSTGRES_USER: "coursework"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coursework -d coursework"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  zookeeper_kafka:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_network

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_kafka:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

  kafka-ui:
    container_name: kafka-ui
    ports:
      - "8086:8080"
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
    networks:
      - kafka_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11-alpine #yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: "coursework"
      CLICKHOUSE_USER: "coursework"
      CLICKHOUSE_PASSWORD: "password"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./chdata:/var/lib/clickhouse
      - ./migrations/clickhouse/allow_window_functions.xml:/etc/clickhouse-server/users.d/allow_experimental_window_functions.xml
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge